const answers = [
    "01B. Where",
    "02A. don’t",
    "03C. Does / speak",
    "04A. Are / making",
    "05C. can’t",
    "06B. my",
    "07D. an old cell phone",
    "08B. in front of / his",
    "09A. know how / very well",
    "10D. How much",
    "11D. some",
    "12A. How often",
    "13D. something",
    "14B. Why / Because",
    "15C. At school",
    "16D. Adam",
    "17A. 433-756-176",
    "18C. He lives in England",
    "19D. Two sisters and two brothers",
    "20B. He goes to the movies and to coffee shops",
    "21A. were",
    "22C. ate / was",
    "23A. Did / help",
    "24C. cheaper than",
    "25A. the most expensive",
    "26B. There aren’t",
    "27D. Whose",
    "28A. Yes, you did.",
    "29B. couldn’t swim",
    "30C. us / was",
    "31A. Would / to go",
    "32D. much",
    "33C. will buy",
    "34A. are / going to start",
    "35B. A large place",
    "36A. 700.",
    "37D. Two bedrooms and two bathrooms.",
    "38D. Spring",
    "39D. South Africa",
    "40C. Mexico",
    "41D. Have / ever",
    "42B. might / forgotten",
    "43A. have been traveling / recently",
    "44A. can’t we",
    "45B. was spoken",
    "46A. has been",
    "47A. have to",
    "48C. must",
    "49B. like / better than",
    "50D. enough",
    "51B. have worked / since",
    "52A. have been thinking",
    "53C. used to",
    "54B. who",
    "55B. a delicious dessert",
    "56B. lime, granola and whipped cream",
    "57A. 15 minutes",
    "58A. Ouside the city limits",
    "59B. It was hidden by ice",
    "60D. There are too many tourists",
    "61D. were / wouldn’t",
    "62A. so / that / each other",
    "63D. hasn’t been found yet",
    "64B. She said she wanted to go home.",
    "65A. hadn’t failed",
    "66A. had",
    "67C. Neither / nor",
    "68A. must have",
    "69C. So do I",
    "70D. would stop",
    "71A. in order to / The more / the worse",
    "72A. unless",
    "73D. In spite of",
    "74C. so / that",
    "75A. An explorer and ecologist",
    "76D. In 1943",
    "77D. To join the United Nations Ecology Conference",
    "78C. Knowing what needs to be done in order to reduce the emission of CO2.",
    "79A. Changing our habits",
    "80D. Various things, from eating habits to the use of energy",
    "81A. in order not to gain",
    "82D. will be studying / will be preparing",
    "83D. no point shouting / has happened",
    "84A. had been thoroughly examined",
    "85D. had studied / would have passed",
    "86C. to extend",
    "87B. wondered",
    "88C. whereas",
    "89A. was supposed / to arrive",
    "90D. however",
    "91A. seems to be",
    "92B. had been running",
    "93B. provided that",
    "94B. have visited",
    "95C. The older generation cannot use technology",
    "96A. Some freak out at the prospect of learning how to use a computer",
    "97D. Because kids have access to all kinds of things: good and bad",
    "98C. By tasting the different flavors",
    "99D. They usually order it according to the number of people",
    "100C. The combination of flavors"
];

export default answers;
